// Followr API resource types.
// All shapes confirmed empirically in discovery sessions 2026-05-13 (rounds 1-6).
// See /docs/followr-api/ for endpoint-level documentation.

export type Iso8601 = string;

export interface FollowrUser {
  id: number;
  name: string | null;
  email: string;
  language?: string | null;
  timezone?: string | null;
  credits?: number;
  has_password?: boolean;
  banned_at?: string | null;
  created_at: Iso8601;
  updated_at: Iso8601;
}

export interface Company {
  id: number;
  name: string;
  type: "company" | "individual";
  description?: string | null;
  website?: string | null;
  user_id?: number;
  country_iso_code?: string | null;
  language?: string | null;
  language_iso_code?: string | null;
  // BYOK keys (do not surface to AI clients)
  ai_keys?: AiKey[];
  // Preferences
  ai_preferences?: AiPreferences;
  // Branding / taste
  ai_image_styles?: unknown[];
  audience_ages?: unknown[];
  audience_genders?: unknown[];
  audience_types?: unknown[];
  characters?: unknown;
  emotions?: unknown;
  fonts?: unknown;
  interests?: unknown[];
  language_types?: unknown[];
  palettes?: unknown[];
  social_network_prompts?: unknown[];
  syntaxes?: unknown;
  tones?: unknown;
  // Webhooks (field on company, no dedicated endpoint)
  webhook_posts_url?: string | null;
  webhook_secret?: string | null;
  // Menu visibility (field on company)
  menu_visibility?: Record<string, boolean>;
  created_at: Iso8601;
  updated_at: Iso8601;
  disabled_at?: string | null;
}

export interface AiKey {
  provider: string;
  api_key?: string;
  is_enabled?: boolean;
}

export interface AiPreferences {
  text_driver?: string;
  text_model?: string;
  image_driver?: string;
  image_model?: string;
  image_aspect_ratio?: string;
  video_driver?: string;
  video_model?: string;
  video_aspect_ratio?: string;
  video_duration?: string | number;
}

export type SocialNetworkType =
  | "instagram"
  | "facebook"
  | "twitter"
  | "linkedin"
  | "tiktok"
  | "youtube"
  | "pinterest"
  | "threads"
  | "bluesky"
  | "medium" // "Blog post" in UI
  | "canva";

export interface PostGroup {
  id: number;
  title: string | null;
  description?: string | null;
  topic?: string | null; // auto-generated by AI
  draft: boolean;
  auto_publish: boolean;
  publish_at: Iso8601 | null;
  tags_ids?: number[];
  user_id?: number | null;
  company_id?: number;
  created_at: Iso8601;
  updated_at: Iso8601;
  posts?: Post[];
  tags?: Tag[];
}

export interface Post {
  id: number;
  social_network_type: SocialNetworkType | string;
  description: string | null;
  title?: string | null;
  link?: string | null;
  assets_ids?: number[];
  preferences?: PostPreferences;
  status?: string;
}

export interface PostPreferences {
  notify_followers?: number | boolean;
  media_product_type?: "FEED" | "REEL" | "STORY" | "SHORT";
  [k: string]: unknown;
}

export interface Tag {
  id: number;
  name: string;
  color?: string | null;
  active?: boolean;
  company_id: number;
  created_at?: Iso8601;
  updated_at?: Iso8601;
}

export interface Folder {
  id: number;
  name: string;
  color?: string | null;
  parent_id?: number | null;
  company_id?: number;
  created_at: Iso8601;
  updated_at: Iso8601;
}

export interface Asset {
  id: number;
  name?: string;
  type: "image" | "video" | "audio";
  url?: string;
  presigned_url?: string;
  width?: number | null;
  height?: number | null;
  size?: number | null;
  duration?: number | null;
  extension?: string;
  driver?: string;
  status?: string;
  visibility?: "public" | "private";
  thumbnail?: Asset | null;
}

export interface Avatar {
  id: number;
  name: string;
  description: string | null;
  default: boolean;
  voice_id: number;
  company_id: number;
  deleted_at?: string | null;
  created_at: Iso8601;
  updated_at: Iso8601;
  image?: Asset | null;
  voice?: Voice;
  scenes?: Scene[];
}

export interface Voice {
  id: number;
  name: string;
  language_code: string;
  platform: string; // e.g. "elevenlabs"
  platform_external_id: string;
  accent?: string | null;
  description?: string | null;
  company_id: number;
  deleted_at?: string | null;
  created_at: Iso8601;
  updated_at: Iso8601;
  audio?: Asset | null;
}

export interface ElevenLabsVoice {
  voice_id: string;
  name: string;
  language?: string;
  locale?: string;
  gender?: string;
  age?: string;
  category?: string;
  description?: string;
  use_case?: string;
  preview_url?: string;
  image_url?: string;
  featured?: boolean;
  [k: string]: unknown;
}

export interface Scene {
  id: number;
  avatar_id?: number;
  script?: string;
  duration?: number;
  order?: number;
  [k: string]: unknown;
}

export interface AiResult {
  id: number;
  type: "chat" | "image" | "video" | "audio";
  driver: string;
  model: string | null;
  status: "pending" | "processing" | "completed" | "failed";
  status_message?: string | null;
  query: string;
  response?: string | null;
  use_own_key?: boolean;
  total_tokens?: number | null;
  words?: number | null;
  created_at: Iso8601 | null;
  updated_at: Iso8601 | null;
  // Note: when status is `completed`, the output URL (image / audio / video)
  // lives in the `response` field above (a string URL on CDN), NOT in
  // dedicated `image_url` / `audio_url` / `video_url` fields. The internal
  // doc previously claimed otherwise; corrected via empirical probe
  // 2026-05-14. For type=chat, `response` is the raw text completion.
}

export interface Conversation {
  id: number;
  externalUser?: ExternalUser;
  external_social_network_id: string;
  social_network_id: number | null;
  external_user_id: number;
  user_id?: number | null;
  last_read_at?: Iso8601;
  unreadMessages_count?: number;
  assistant_message_enabled?: boolean;
  lastMessage?: Message;
  image?: unknown;
  created_at: Iso8601;
  updated_at: Iso8601;
}

export interface ExternalUser {
  id: number;
  company_id: number;
  name: string | null;
  username: string | null;
  external_id: string;
  type: string;
  description?: string | null;
  last_interaction_at?: Iso8601 | null;
  image?: unknown;
  created_at: Iso8601;
  updated_at: Iso8601;
}

export interface Message {
  id: number;
  conversation_id: number;
  message: string;
  sender: string;
  external_id?: string;
  dispatch_at?: Iso8601;
  created_at: Iso8601;
  updated_at: Iso8601;
}

/**
 * Brand-voice prompt resource. The Followr UI calls these "Prompts" under
 * Company Settings → Prompts and lets the user create multiple variants per
 * social network, marking one or more as default. When AI content generation
 * runs (Post Generator, etc.), Followr picks among the prompts where
 * `default=true` for the relevant `social_network_type`.
 *
 * Note: there is also a legacy denormalized field `Company.social_network_prompts`
 * that mirrors a slice of this resource, but it is read-only via PUT
 * /api/companies/{id}. Always mutate via the /api/prompts endpoints.
 */
export interface Prompt {
  id: number;
  user_id: number;
  /** Null when the prompt is a Followr built-in default; numeric for workspace-scoped prompts. */
  company_id: number | null;
  type: string;
  social_network_type: SocialNetworkType | string;
  default: boolean;
  name: string;
  prompt: string;
  created_at: Iso8601;
  updated_at: Iso8601;
}

export interface RuleGroup {
  id: number;
  name: string;
  description?: string | null;
  active: boolean;
  random_minutes: number;
  company_id: number;
  created_at: Iso8601;
  updated_at: Iso8601;
  rules?: Rule[];
}

export interface Rule {
  id: number;
  tags_ids?: number[];
  days_of_week?: string[];
  time_slots?: string[];
  social_network_types?: string[];
}

export interface SocialNetwork {
  id: number;
  type: SocialNetworkType | string;
  status?: string | null;
}

export interface CanvaDesign {
  id: string;
  title: string;
  page_count: number;
  thumbnail: { url: string; width: number; height: number };
  urls: { edit_url: string; view_url: string };
  owner: { team_id: string; user_id: string };
  created_at: number;
  updated_at: number;
}

export interface SubscriptionBalance {
  credits: number;
  words_allowed: number;
  words_spent: number;
  words_renews_at: Iso8601;
  images_allowed: number;
  images_spent: number;
  premium_images_allowed: number;
  premium_images_spent: number;
  images_bonus_total: number;
  images_bonus_credits: unknown[];
  bytes_allowed: number;
  bytes_spent: string;
  companies_allowed: number;
  companies_spent: number;
  users_allowed: number;
  users_spent: number;
  api_keys_enabled?: boolean;
  getlead_enabled: boolean;
  plus_chat_enabled: boolean;
  white_label_enabled: boolean;
}

export interface ApiCollection<T> {
  data: T[];
  meta?: {
    current_page: number;
    last_page: number;
    from: number | null;
    to: number | null;
    total: number;
    per_page: number;
    path?: string;
    links?: Array<{ url: string | null; label: string; active: boolean }>;
  };
  links?: { first: string; last: string; next: string | null; prev: string | null };
}

export interface ApiSingle<T> {
  data: T;
}
